# Generated by Django 5.2.2 on 2025-06-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('autor', 'Autor'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], default='cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, default='default@example.com', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
