# Generated by Django 5.2.2 on 2025-06-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario_tipo_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador'), ('autor', 'Autor'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], default='cliente', max_length=20),
        ),
    ]
