# Generated by Django 5.2.2 on 2025-06-19 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0004_alter_producto_stock_minimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('venta', 'Venta'), ('reparacion', 'Reparación')], max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del pedido o requerimiento del cliente')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('produccion', 'En producción'), ('envio', 'En camino'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('cliente', 'Cambio de Cliente'), ('estado', 'Cambio de Estado'), ('producto', 'Cambio de Producto'), ('cantidad', 'Cambio de Cantidad')], max_length=20)),
                ('cliente_anterior', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nuevo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('cantidad_anterior', models.IntegerField(blank=True, null=True)),
                ('cantidad_nueva', models.IntegerField(blank=True, null=True)),
                ('producto_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('producto_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Historial de Pedido',
                'verbose_name_plural': 'Historial de Pedidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
