# Generated by Django 5.2.2 on 2025-06-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedido',
            name='fecha_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='fecha_nueva',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='tipo_cambio',
            field=models.CharField(choices=[('cliente', 'Cambio de Cliente'), ('estado', 'Cambio de Estado'), ('producto', 'Cambio de Producto'), ('cantidad', 'Cambio de Cantidad'), ('fecha_estimada', 'Cambio de Fecha Estimada'), ('fecha_real', 'Cambio de Fecha Real')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador/Pendiente'), ('confirmado', 'Confirmado'), ('produccion', 'En Producción'), ('terminacion', 'En Terminación'), ('terminado', 'Terminado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
    ]
