# Generated by Django 5.2.2 on 2025-06-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_historialpedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpedido',
            name='observacion',
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_anterior',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_nuevo',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
