# Generated by Django 5.2.2 on 2025-06-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
