# Generated by Django 5.2.2 on 2025-06-18 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_historialpedido_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpedido',
            name='cantidad_anterior',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='cantidad_nueva',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='cliente',
            field=models.CharField(default='desconocido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='producto_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='producto_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_anterior',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_nuevo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
    ]
