# Generated by Django 5.2.2 on 2025-06-18 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_historialpedido_cantidad_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpedido',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido'),
        ),
    ]
