# Generated by Django 5.2.2 on 2025-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_fecha_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
