# Generated by Django 5.2.2 on 2025-06-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_historialpedido_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpedido',
            name='cantidad_anterior',
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='cliente_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='cliente_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
