# Generated by Django 5.2.2 on 2025-06-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_historialpedido_cantidad_anterior_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialpedido',
            name='cliente_anterior',
        ),
        migrations.RemoveField(
            model_name='historialpedido',
            name='cliente_nuevo',
        ),
        migrations.AddField(
            model_name='historialpedido',
            name='cantidad_anterior',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='cantidad_nueva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='estado_nuevo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='producto_anterior',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='producto_nuevo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
